// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Site           string `path:"site"`
	Import         bool   `form:"import,optional,default=1"`
	Export         bool   `form:"export,optional,default=1"`
	Alias          bool   `form:"alias,optional,default=1"`
	TestDataSource bool   `form:"testds,optional,default=0"`
	Debug          bool   `form:"debug,optional,default=0"`
}

type Response struct {
	Message string `json:"message"`
}

type SynonymHeadRequest struct {
	Site           string `path:"site"`
	LastUpdateTime string `header:"If-Modified-Since,optional"`
	Etag           string `header:"If-None-Match,optional"`
}

type SynonymHeadResponse struct {
	ETag         string `head:"ETag"`
	LastModified string `head:"Last-Modified"`
}

type SynonymRequest struct {
	Site string `path:"site"`
	Lang string `path:"lang"`
}

type SynonymResponse struct {
	Synonym []byte `json:"synonym"`
}
