// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"sqlsyncify/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: RootHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/clean/noalias/:site",
				Handler: CleanNoAliasHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/clean/noalias/v5/:site",
				Handler: CleanNoAliasV5Handler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/sync/all/:site",
				Handler: SqlsyncifyAllHandler(serverCtx),
			},
			{
				Method:  http.MethodHead,
				Path:    "/synonym/:site",
				Handler: SynonymHeadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/synonym/:site",
				Handler: SynonymHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/synonym/:site",
				Handler: SynonymHandler(serverCtx),
			},
		},
	)
}
